version: '3.7'

services:
    db-devel:
        image: postgres:12.0-alpine
        volumes:
            - casino_data_dev:/var/lib/postgresql/data/
        restart: always
        ports:
            - 127.0.0.1:5435:5432
        environment:
            - POSTGRES_USER=pablodevuser
            - POSTGRES_PASSWORD=9282jjssssds
            - POSTGRES_DB=casinodev

volumes:
    casino_data_dev:
