# Generated by Django 4.0.4 on 2022-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='roi',
            field=models.FloatField(default=0),
        ),
    ]
