# Generated by Django 4.0.4 on 2022-05-31 13:46

import django.contrib.postgres.fields
from django.db import migrations, models
import machine.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_roi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='configuration',
        ),
        migrations.AddField(
            model_name='machine',
            name='bonus_reel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=machine.models.Machine.empty_list, size=5),
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='machine',
            name='normal_reel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=machine.models.Machine.empty_list, size=5),
        ),
        migrations.AddField(
            model_name='machine',
            name='visible',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=machine.models.Machine.empty_list, size=5),
        ),
        migrations.AlterField(
            model_name='machine',
            name='free_spins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=machine.models.Machine.empty_list, size=5),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reels_round',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=machine.models.Machine.empty_list, size=5),
        ),
    ]
