# Generated by Django 4.0.4 on 2022-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_remove_machine_reels_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='multiplier',
            field=models.IntegerField(default=3),
        ),
    ]
